apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-agent-blue
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-branch-blue
  template:
    metadata:
      labels:
        app: multi-branch-blue
    spec:
      containers:
      - name: multi-agent-blue
        image: ambarbhore1234/multi-branch-agent:placeholder
        ports:
        - containerPort: 9090
        livenessProbe:
          httpGet: 
            path: /healthz
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
      imagePullSecrets:
      - name: dockerhub-cred-prod
