apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-branch
  namespace: dev1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-branch
  template:
    metadata:
      labels:
        app: multi-branch
    spec:
      containers:
      - name: multi-branch
        image: ambarbhore1234/multi-branch-agent:placeholder
        ports:
        - containerPort: 9090
        livenessProbe:
          httpGet: 
            path: /healthz
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
      imagePullSecrets:
      - name: dockerhub-cred
